// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("New Test", function () {
    this.timeout(30000);
    let driver;
    let vars;

    beforeEach(async function () {
        driver = await new Builder().forBrowser("chrome").build();
        vars = {};
    });
    afterEach(async function () {
        await driver.quit();
    });
    it("New Test", async function () {
        await driver.get("http://localhost:3111/");
        await driver.findElement(By.id("UDP_ID_5")).click();
        await driver.findElement(By.id("UDP_ID_6")).click();
        await driver.findElement(By.id("UDP_ID_7")).click();
        await driver.findElement(By.id("UDP_ID_8")).click();
    });
});
